language: php

php:
# - '5.6'
  - '7.0'
  - '7.1'
  - '7.2'

before_install:
  - composer self-update

install:
  - composer install

script:
  - composer test

after_success:
  - travis_retry php vendor/bin/php-coveralls

